const ACTION_ADD = 'ADD';
const ACTION_COMPLETE = 'COMPLETE';
const ACTION_TOGGLE_COMPLETION = 'TOGGLE_COMPLETION';
const ACTION_DELETE = 'DELETE';

export {
  ACTION_ADD,
  ACTION_COMPLETE,
  ACTION_TOGGLE_COMPLETION,
  ACTION_DELETE,
}
